name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          brew install gtk+3
          python3 -m pip install -r requirements.txt
          python3 -m pip install pytest
      - name: Test with pytest
        run: |
          python3 -m pytest test.py

  test_ubuntu_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install pytest
      - name: Test with pytest
        run: |
          python3 -m pytest test.py

  test_ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install pytest
      - name: Test with pytest
        run: |
          python3 -m pytest test.py